import { User } from "../../interfaces/user";

export const users:User[] =[
    {
        id:1,
        name:'Anurag',
        address:'Jagamara',
        email:'sa@gmail.com',
        phone:785965878,
        designation:'Backend Developer',
    },
    {
        id:2,
        name:'Santosh',
        address:'Balasore',
        email:'santosh@gmail.com',
        phone:9898981212,
        designation:'Backend Developer',
    },
    {
        id:3,
        name:'Surya',
        address:'Dhenkanal',
        email:'surya@gmail.com',
        phone:9767656743,
        designation:'Backend Developer',
    },
    {
        id:4,
        name:'Soumya',
        address:'Kendrapada',
        email:'soumya@gmail.com',
        phone:8989890909,
        designation:'Backend Developer',
    },
    {
        id:6,
        name:'Sandeep',
        address:'Acharya Vihar',
        email:'sandeep@gmail.com',
        phone:9090909090,
        designation:'Backend Developer',
    },
    {
        id:7,
        name:'Sunil',
        address:'Balakati',
        email:'sunil@gmail.com',
        phone:9090909090,
        designation:'Frontend Developer',
    },
    {
        id:8,
        name:'Satyabrata',
        address:'Velanga',
        email:'satya@gmail.com',
        phone:9090909090,
        designation:'Frontend Developer',
    },
    {
        id:9,
        name:'Sohel',
        address:'Korai',
        email:'sohel@gmail.com',
        phone:9090909090,
        designation:'Backend Developer',
    },
    {
        id:10,
        name:'Sankar',
        address:'Dhenkanal',
        email:'sankar@gmail.com',
        phone:9090909090,
        designation:'Backend Developer',
    },
];